tables = {
                "001": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "DataRelease", "length": 4},
                    {"name": "VersionDate", "length": 8},
                    {"name": "Full_", "length": 1},
                    {"name": "ManNo", "length": 6},
                    {"name": "BrandName", "length": 20},
                    {"name": "RefDataVersion", "length": 4},
                    {"name": "Reserved", "length": 4},
                    {"name": "Format", "length": 3},
                    {"name": "D_leteFlag", "length": 1}
                ],
                "010": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "CountryCode", "length": 3},
                    {"name": "TermNo", "length": 9},
                    {"name": "Traffic", "length": 1},
                    {"name": "CurNo", "length": 3},
                    {"name": "CurCode", "length": 3},
                    {"name": "CurTermNo", "length": 9},
                    {"name": "AreaCode", "length": 5},
                    {"name": "IsGroup", "length": 1},
                    {"name": "ISOCode2", "length": 2},
                    {"name": "ISOCode3", "length": 3},
                    {"name": "ISOCodeNo", "length": 3}
                ],
                "012": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "CTermNo", "length": 9},
                    {"name": "CountryCode", "length": 3},
                    {"name": "LanguageNo", "length": 3},
                    {"name": "Term", "length": 60}
                ],
                "013": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "CountryGrp", "length": 3},
                    {"name": "CountryCode", "length": 3}
                ],
                "014": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "DocType", "length": 2},
                    {"name": "TermNo", "length": 9},
                    {"name": "Extension", "length": 3}
                ],
                "020": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "LangNo", "length": 3},
                    {"name": "TermNo", "length": 9},
                    {"name": "ISOCode", "length": 2},
                    {"name": "Codepage", "length": 4}
                ],
                "030": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "TermNo", "length": 9},
                    {"name": "LangNo", "length": 3},
                    {"name": "Term", "length": 60},
                    {"name": "D_leteFlag", "length": 1}
                ],
                "031": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "TermNo", "length": 9},
                    {"name": "LangNo", "length": 3},
                    {"name": "Term", "length": 60},
                ],
                "035": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "TxtModNo", "length": 6},
                    {"name": "LangNo", "length": 3},
                    {"name": "Fixed", "length": 1},
                    {"name": "SeqNo", "length": 3},
                    {"name": "Text", "length": 60},
                    {"name": "D_leteFlag", "length": 1}
                ],
                "040": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "Term1", "length": 40},
                    {"name": "Term2", "length": 40},
                    {"name": "Street1", "length": 40},
                    {"name": "Street2", "length": 40},
                    {"name": "POBox", "length": 10},
                    {"name": "CountryPrefix", "length": 3},
                    {"name": "PostCode", "length": 8},
                    {"name": "PostCodePOBox", "length": 8},
                    {"name": "PostCodeCus", "length": 8},
                    {"name": "City1", "length": 40},
                    {"name": "City2", "length": 40},
                    {"name": "Phone", "length": 20},
                    {"name": "Fax", "length": 20},
                    {"name": "Email", "length": 60},
                    {"name": "Web", "length": 60},
                    {"name": "AdrType", "length": 3},
                    {"name": "D_leteFlag", "length": 1}
                ],
                "042": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "CountryCode", "length": 3},
                    {"name": "DocNo", "length": 9},
                    {"name": "DocType", "length": 2},
                    {"name": "D_leteFlag", "length": 1},
                ],
                "043": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "AdrType", "length": 3},
                    {"name": "CountryCode", "length": 3},
                    {"name": "Term1", "length": 40},
                    {"name": "Term2", "length": 40},
                    {"name": "Street1", "length": 40},
                    {"name": "Street2", "length": 40},
                    {"name": "POBox", "length": 10},
                    {"name": "CountryPrefix", "length": 3},
                    {"name": "PostCode", "length": 8},
                    {"name": "PostCodePOBox", "length": 8},
                    {"name": "PostCodeCus", "length": 8},
                    {"name": "City1", "length": 40},
                    {"name": "City2", "length": 40},
                    {"name": "Phone", "length": 20},
                    {"name": "Fax", "length": 20},
                    {"name": "Email", "length": 60},
                    {"name": "Web", "length": 60},
                    {"name": "Adr_Type", "length": 1}
                ],
                "050": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "CritNo", "length": 4},
                    {"name": "TermNo", "length": 9},
                    {"name": "Type", "length": 1},
                    {"name": "MaxLen", "length": 2},
                    {"name": "OKArticle", "length": 1},
                    {"name": "TabNo", "length": 3},
                    {"name": "OKCV", "length": 1},
                    {"name": "OKPC", "length": 1},
                    {"name": "OKEngine", "length": 1},
                    {"name": "OKDrivCab", "length": 1},
                    {"name": "PartLstCrit", "length": 1},
                    {"name": "AccCrit", "length": 1},
                    {"name": "Multiple", "length": 1},
                    {"name": "TermNoAbbr", "length": 9},
                    {"name": "TermNoUnit", "length": 9},
                    {"name": "IntervalCrit", "length": 1},
                    {"name": "SuccCrit", "length": 4},
                    {"name": "D_lete", "length": 1},
                    {"name": "OKAxle", "length": 1}
                ],
                "051": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "KeyTabNo", "length": 3},
                    {"name": "TermNo", "length": 9},
                    {"name": "KeyTabType", "length": 1},
                    {"name": "D_lete", "length": 1}
                ],
                "052": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "KeyTabNo", "length": 3},
                    {"name": "K_ey", "length": 3},
                    {"name": "TermNo", "length": 9},
                    {"name": "SortNo", "length": 3},
                    {"name": "D_lete", "length": 1}
                ],
                "053": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "CritNo", "length": 4},
                    {"name": "TermNo", "length": 9},
                    {"name": "Type", "length": 1},
                    {"name": "MaxLen", "length": 2},
                    {"name": "OKArtikel", "length": 1},
                    {"name": "TabNo", "length": 3},
                    {"name": "OKCV", "length": 1},
                    {"name": "OKPC", "length": 1},
                    {"name": "OKEngine", "length": 1},
                    {"name": "OKDrivCab", "length": 1},
                    {"name": "PartLstCrit", "length": 1},
                    {"name": "AccCrit", "length": 1},
                    {"name": "Multiple", "length": 1},
                    {"name": "TermNoAbbr", "length": 9},
                    {"name": "TermNoUnit", "length": 9},
                    {"name": "IntervalCrit", "length": 1},
                    {"name": "SuccCrit", "length": 4},
                    {"name": "D_lete", "length": 1},
                    {"name": "OKAxle", "length": 1}
                ],
                "100": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "ManNo", "length": 6},
                    {"name": "ManCode", "length": 10},
                    {"name": "CTermNo", "length": 9},
                    {"name": "PC", "length": 1},
                    {"name": "CV", "length": 1},
                    {"name": "Compare", "length": 1},
                    {"name": "Axle", "length": 1},
                    {"name": "Engine", "length": 1},
                    {"name": "Transmission", "length": 1},
                    {"name": "LCV", "length": 1},
                    {"name": "D_lete", "length": 1}
                ],
                "103": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "KBANo", "length": 4},
                    {"name": "ManNo", "length": 6}
                ],
                "110": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "KModNo", "length": 5},
                    {"name": "CTermNo", "length": 9},
                    {"name": "ManNo", "length": 6},
                    {"name": "SortNo", "length": 3},
                    {"name": "ModYFrom", "length": 6},
                    {"name": "ModYTo", "length": 6},
                    {"name": "PC", "length": 1},
                    {"name": "CV", "length": 1},
                    {"name": "Axle", "length": 1},
                    {"name": "D_lete", "length": 1},
                    {"name": "LCV", "length": 1}
                ],
                "115": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "LinkageTargetNo", "length": 9},
                    {"name": "LinkageTargetTable", "length": 3},
                    {"name": "LTTypeOriginal", "length": 3},
                    {"name": "LTTypeExtended", "length": 3}
                ],
                "120": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "KTypNo", "length": 9},
                    {"name": "CTermNo", "length": 9},
                    {"name": "KModNo", "length": 5},
                    {"name": "SortNo", "length": 2},
                    {"name": "ModYFrom", "length": 6},
                    {"name": "ModYTo", "length": 6},
                    {"name": "KW", "length": 4},
                    {"name": "HP", "length": 4},
                    {"name": "ccmTax", "length": 5},
                    {"name": "ccmTech", "length": 5},
                    {"name": "Lit", "length": 4},
                    {"name": "Cyl", "length": 2},
                    {"name": "Doors", "length": 1},
                    {"name": "TankCap", "length": 4},
                    {"name": "Voltage", "length": 2},
                    {"name": "ABS", "length": 1},
                    {"name": "TCS", "length": 1},
                    {"name": "EngType", "length": 3},
                    {"name": "FuelMixForm", "length": 3},
                    {"name": "DriveType", "length": 3},
                    {"name": "BrakeType", "length": 3},
                    {"name": "BrakeSys", "length": 3},
                    {"name": "Valves", "length": 2},
                    {"name": "FuelType", "length": 3},
                    {"name": "CatType", "length": 3},
                    {"name": "TransmType", "length": 3},
                    {"name": "BodyType", "length": 3},
                    {"name": "D_lete", "length": 1}
                ],
                "121": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "KBANo", "length": 7},
                    {"name": "KTypNo", "length": 9},
                    {"name": "BodyType", "length": 3},
                    {"name": "ABENo", "length": 25},
                    {"name": "ABEfrom", "length": 6},
                    {"name": "StatMan", "length": 25},
                    {"name": "StatType", "length": 25}
                ],
                "122": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "KTypNo", "length": 9},
                    {"name": "CountryCode", "length": 3},
                    {"name": "Exclude", "length": 1}
                ],
                "123": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "TypMine", "length": 15},
                    {"name": "KTypNo", "length": 9}
                ],
                "124": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "KTypNo", "length": 9},
                    {"name": "CountryCode", "length": 3},
                    {"name": "ModYFrom", "length": 6},
                    {"name": "ModYTo", "length": 6},
                    {"name": "ccmTax", "length": 5},
                    {"name": "Lit", "length": 4},
                    {"name": "Cyl", "length": 2},
                    {"name": "Doors", "length": 1},
                    {"name": "TankCap", "length": 4},
                    {"name": "Voltage", "length": 2},
                    {"name": "ABS", "length": 1},
                    {"name": "TCS", "length": 1},
                    {"name": "FuelType", "length": 3},
                    {"name": "CatType", "length": 3},
                    {"name": "TransmType", "length": 3},
                    {"name": "BrakeType", "length": 3},
                    {"name": "BrakeSys", "length": 3}
                ],
                "125": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "KTypNo", "length": 9},
                    {"name": "SeqNo", "length": 3},
                    {"name": "EngNo", "length": 5},
                    {"name": "ModYFrom", "length": 6},
                    {"name": "ModYTo", "length": 6},
                    {"name": "CountryCode", "length": 3},
                    {"name": "Exclude", "length": 1}
                ],
                "126": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "ChTyp", "length": 7},
                    {"name": "KTypNo", "length": 9},
                ],
                "127": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "NLTyp", "length": 6},
                    {"name": "KTypNo", "length": 9},
                ],
                "128": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "STyp", "length": 6},
                    {"name": "KTypNo", "length": 9},
                ],
                "129": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "STyp", "length": 6},
                    {"name": "KTypNo", "length": 9},
                ],
                "140": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "KModNo", "length": 5},
                    {"name": "CTermNo1", "length": 9},
                    {"name": "CTermNo2", "length": 9}
                ],
                "143": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "KmodNo", "length": 5},
                    {"name": "CountryCode", "length": 3},
                    {"name": "SortNo", "length": 4},
                    {"name": "ModelType", "length": 10}
                ],
                "144": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "KTypNo", "length": 9},
                    {"name": "CTermNo1", "length": 9},
                    {"name": "CTErmNo2", "length": 9}
                ],
                "145": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "KTypNo", "length": 9},
                    {"name": "CountryCode", "length": 3},
                    {"name": "SortNo", "length": 4},
                    {"name": "ModelType", "length": 10}
                ],
                "146": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "BodyType", "length": 3},
                    {"name": "KModNo", "length": 5},
                    {"name": "CTermNo", "length": 9}
                ],
                "147": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "DriveType", "length": 3},
                    {"name": "KTypNo", "length": 9},
                    {"name": "CTermNo", "length": 9}
                ],
                "155": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "ManNo", "length": 6},
                    {"name": "EngNo", "length": 5},
                    {"name": "EngCode", "length": 60},
                    {"name": "ModYFrom", "length": 6},
                    {"name": "ModYTo", "length": 6},
                    {"name": "kWFrom", "length": 4},
                    {"name": "kWTo", "length": 4},
                    {"name": "HPFrom", "length": 4},
                    {"name": "HPTo", "length": 4},
                    {"name": "Valves", "length": 2},
                    {"name": "Cyl", "length": 2},
                    {"name": "ComprFrom", "length": 4},
                    {"name": "ComprTo", "length": 5},
                    {"name": "TorqFrom", "length": 4},
                    {"name": "ToryTo", "length": 5},
                    {"name": "ccTaxFrom", "length": 5},
                    {"name": "ccTaxTo", "length": 5},
                    {"name": "ccTechFrom", "length": 5},
                    {"name": "ccTechTo", "length": 5},
                    {"name": "litTaxFrom", "length": 4},
                    {"name": "litTaxTo", "length": 4},
                    {"name": "litTechFrom", "length": 4},
                    {"name": "litTechTo", "length": 4},
                    {"name": "EngUse", "length": 3},
                    {"name": "EngDesign", "length": 3},
                    {"name": "FuelType", "length": 3},
                    {"name": "FuelMixForm", "length": 3},
                    {"name": "EngAsp", "length": 3},
                    {"name": "RPMkWFrom", "length": 5},
                    {"name": "RPMkWTo", "length": 5},
                    {"name": "RPMTorqFrom", "length": 5},
                    {"name": "RPMTorqTo", "length": 5},
                    {"name": "CrankBearQuant", "length": 2},
                    {"name": "Bore", "length": 6},
                    {"name": "Stroke", "length": 6},
                    {"name": "EngType", "length": 3},
                    {"name": "ExhNorm", "length": 3},
                    {"name": "CylDesign", "length": 3},
                    {"name": "EngMngmnt", "length": 3},
                    {"name": "ValveCtrl", "length": 3},
                    {"name": "CoolType", "length": 3},
                    {"name": "SalesTerm", "length": 30},
                    {"name": "Exclude", "length": 1},
                    {"name": "D_lete", "length": 1}
                ],
                "156": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "EngNo", "length": 5},
                    {"name": "CountryCode", "length": 3}
                ],
                "160": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "ATypNo", "length": 5},
                    {"name": "Term", "length": 30},
                    {"name": "KmodNo", "length": 5},
                    {"name": "SortNo", "length": 4},
                    {"name": "ModYFrom", "length": 6},
                    {"name": "ModYTo", "length": 6},
                    {"name": "AxleType", "length": 3},
                    {"name": "AxleStyle", "length": 3},
                    {"name": "BrakeType", "length": 3},
                    {"name": "AxleBody", "length": 3},
                    {"name": "MaxLoadFrom", "length": 5},
                    {"name": "MaxLoadTo", "length": 5},
                    {"name": "WheelMount", "length": 3},
                    {"name": "TrWidth", "length": 4},
                    {"name": "HubWidth", "length": 20},
                    {"name": "DrivHeightFrom", "length": 4},
                    {"name": "DdrivHeightTo", "length": 4},
                    {"name": "D_lete", "length": 1}
                ],
                "161": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "ATypNo", "length": 5},
                    {"name": "CountryCode", "length": 3},
                    {"name": "SortNo", "length": 4},
                    {"name": "BodyType", "length": 20}
                ],
                "162": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "ATypNo", "length": 5},
                    {"name": "SeqNo", "length": 3},
                    {"name": "SortNo", "length": 3},
                    {"name": "AxlePos", "length": 3},
                    {"name": "Wheelbase", "length": 6}
                ],
                "163": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "ATypNo", "length": 5},
                    {"name": "SeqNo", "length": 3},
                    {"name": "BrakeSze", "length": 3},
                    {"name": "BrTerm", "length": 20}
                ],
                "164": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "NTypNo", "length": 9},
                    {"name": "SeqNo", "length": 3},
                    {"name": "SortNo", "length": 3},
                    {"name": "ATypNo", "length": 5},
                    {"name": "AxlePos", "length": 3},
                    {"name": "ModYFrom", "length": 6},
                    {"name": "ModYTo", "length": 6},
                    {"name": "CountryCode", "length": 3},
                    {"name": "Exclude", "length": 1}
                ],
                "200": [
                    {"name": "ArtNo", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "TermNo", "length": 9},
                    {"name": "SelfServ", "length": 1},
                    {"name": "MatCert", "length": 1},
                    {"name": "Remanufact", "length": 1},
                    {"name": "Accessory", "length": 1},
                    {"name": "BatchSize1", "length": 5},
                    {"name": "BatchSize2", "length": 5},
                    {"name": "D_leteFlag", "length": 1}
                ],
                "201": [
                    {"name": "ArtNo", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "Price", "length": 10},
                    {"name": "PrUnit", "length": 3},
                    {"name": "PrQuantUnit", "length": 3},
                    {"name": "ValidFrom", "length": 8},
                    {"name": "ValidTo", "length": 8},
                    {"name": "CountryCode", "length": 3},
                    {"name": "PrType", "length": 3},
                    {"name": "Reserved", "length": 10},
                    {"name": "CurCode", "length": 3},
                    {"name": "DiscGroup", "length": 5},
                    {"name": "Dicount", "length": 1},
                    {"name": "D_leteFlag", "length": 1},
                ],
                "202": [
                    {"name": "ArtNo", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "CountryCode", "length": 3},
                    {"name": "Exclude", "length": 1},
                    {"name": "D_leteFlag", "length": 1},
                ],
                "203": [
                    {"name": "ArtNo", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "ManNo", "length": 6},
                    {"name": "CountryCode", "length": 3},
                    {"name": "RefNo", "length": 22},
                    {"name": "Exclude", "length": 1},
                    {"name": "SortNo", "length": 5},
                    {"name": "Additive", "length": 1},
                    {"name": "ReferenceInfo", "length": 3},
                    {"name": "D_leteFlag", "length": 1},
                ],
                "204": [
                    {"name": "ArtNo", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "CountryCode", "length": 3},
                    {"name": "SupersNo", "length": 22},
                    {"name": "Exclude", "length": 1},
                    {"name": "SortNo", "length": 5},
                    {"name": "D_leteFlag", "length": 1},
                ],
                "205": [
                    {"name": "ArtNo", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "PartGenArtNo", "length": 5},
                    {"name": "SeqNo", "length": 3},
                    {"name": "PartNo", "length": 22},
                    {"name": "Quantity", "length": 3},
                    {"name": "D_leteFlag", "length": 1},
                ],
                "206": [
                    {"name": "ArtNo", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "Reserved", "length": 5},
                    {"name": "CountryCode", "length": 3},
                    {"name": "SortNo", "length": 2},
                    {"name": "InfType", "length": 3},
                    {"name": "FirstPage", "length": 1},
                    {"name": "TXTModNo", "length": 6},
                    {"name": "Exclude", "length": 1},
                    {"name": "D_leteFlag", "length": 1}
                ],
                "207": [
                    {"name": "ArtNo", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "CountryCode", "length": 3},
                    {"name": "TradeNo", "length": 35},
                    {"name": "Exclude", "length": 1},
                    {"name": "FirstPage", "length": 1},
                    {"name": "SortNo", "length": 5},
                    {"name": "D_leteFlag", "length": 1}
                ],
                "208": [
                    {"name": "ArtNo", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "Reserved1", "length": 3},
                    {"name": "SeqNo", "length": 5},
                    {"name": "SortNo", "length": 3},
                    {"name": "CritNo", "length": 4},
                    {"name": "CritVal", "length": 20},
                    {"name": "Reserved", "length": 1},
                    {"name": "SeqNo1", "length": 3},
                    {"name": "D_leteFlag", "length": 1}
                ],
                "209": [
                    {"name": "ArtNo", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "CountryCode", "length": 3},
                    {"name": "GTIN", "length": 13},
                    {"name": "Exclude", "length": 1},
                    {"name": "D_leteFlag", "length": 1}
                ],
                "210": [
                    {"name": "ArtNo", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "Reserved", "length": 5},
                    {"name": "CountryCode", "length": 3},
                    {"name": "SortNo", "length": 3},
                    {"name": "CritNo", "length": 4},
                    {"name": "CritVal", "length": 20},
                    {"name": "FirstPage", "length": 1},
                    {"name": "Exclude", "length": 1},
                    {"name": "D_leteFlag", "length": 1}
                ],
                "211": [
                    {"name": "ArtNo", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "GenArtNo", "length": 5},
                    {"name": "D_leteFlag", "length": 1}
                ],
                "212": [
                    {"name": "ArtNo", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "CountryCode", "length": 3},
                    {"name": "QuantUnit", "length": 5},
                    {"name": "QuantPerUnit", "length": 5},
                    {"name": "ArtStat", "length": 3},
                    {"name": "StatusDat", "length": 8},
                    {"name": "D_leteFlag", "length": 1}
                ],
                "213": [
                    {"name": "ArtNo", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "CountryCode", "length": 3},
                    {"name": "SortNo", "length": 3},
                    {"name": "CritNo", "length": 4},
                    {"name": "CritVal", "length": 20},
                    {"name": "FirstPage", "length": 1},
                    {"name": "Exclude", "length": 1}
                ],
                "215": [
                    {"name": "ArtNo", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "SeqNo", "length": 3},
                    {"name": "CountryCode", "length": 3},
                    {"name": "Exclude", "length": 1},
                    {"name": "D_leteFlag", "length": 1}
                ],
                "217": [
                    {"name": "ArtNo", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "SeqNo", "length": 3},
                    {"name": "DocNo", "length": 9},
                    {"name": "DocType", "length": 2},
                    {"name": "LangNo", "length": 3},
                    {"name": "CoordNo", "length": 4},
                    {"name": "D_leteFlag", "length": 1}
                ],
                "222": [
                    {"name": "ArtNo", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "LnkType", "length": 1},
                    {"name": "LnkVal", "length": 6},
                    {"name": "SeqNo", "length": 3},
                    {"name": "SortNo", "length": 3},
                    {"name": "AccArtNo", "length": 22},
                    {"name": "Quantity", "length": 3},
                    {"name": "AccGenArtNo", "length": 5},
                    {"name": "Reserved", "length": 1},
                    {"name": "TermNo", "length": 9},
                    {"name": "D_leteFlag", "length": 1},
                ],
                "228": [
                    {"name": "ArtNo", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "CountryCode", "length": 3},
                    {"name": "SeqNo1", "length": 3},
                    {"name": "SortNo1", "length": 3},
                    {"name": "SeqNo", "length": 3},
                    {"name": "CritNo", "length": 4},
                    {"name": "CritVal", "length": 20},
                    {"name": "Exclude", "length": 1},
                    {"name": "D_leteFlag", "length": 1}
                ],
                "231": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "DocNo", "length": 9},
                    {"name": "LangNo", "length": 3},
                    {"name": "DocName", "length": 30},
                    {"name": "DocContentType", "length": 3},
                    {"name": "DocTermNorm", "length": 3},
                    {"name": "Width", "length": 4},
                    {"name": "Height", "length": 4},
                    {"name": "Colors", "length": 3},
                    {"name": "DocType", "length": 2},
                    {"name": "TermNo", "length": 9},
                    {"name": "D_leteFlag", "length": 1},
                    {"name": "URL", "length": 300}
                ],
                "232": [
                    {"name": "ArtNo", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "SortNo", "length": 2},
                    {"name": "CountryCode", "length": 3},
                    {"name": "Exclude", "length": 1},
                    {"name": "DocNo", "length": 9},
                    {"name": "DocType", "length": 2},
                    {"name": "D_leteFlag", "length": 1}
                ],
                "233": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "DocNo", "length": 9},
                    {"name": "DocType", "length": 2},
                    {"name": "CoordNo", "length": 4},
                    {"name": "SeqNo", "length": 3},
                    {"name": "LangNo", "length": 3},
                    {"name": "Type", "length": 1},
                    {"name": "X1", "length": 4},
                    {"name": "Y1", "length": 4},
                    {"name": "X2", "length": 4},
                    {"name": "Y2", "length": 4},
                    {"name": "D_leteFlag", "length": 1}
                ],
                "301": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "Node_ID", "length": 7},
                    {"name": "TreeTypNo", "length": 3},
                    {"name": "Level", "length": 2},
                    {"name": "Node_Parent_ID", "length": 7},
                    {"name": "SortNo", "length": 2},
                    {"name": "TermNo", "length": 9},
                    {"name": "GenArtOK", "length": 1}
                ],
                "302": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "Node_ID", "length": 7},
                    {"name": "SortNo", "length": 2},
                    {"name": "GenArtNo", "length": 5}
                ],
                "304": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "Node_ID", "length": 7},
                    {"name": "GenArtNo", "length": 5},
                    {"name": "SortNo", "length": 3},
                    {"name": "CritNo", "length": 4},
                    {"name": "CritVal", "length": 20}
                ],
                "305": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "QS_Id", "length": 4},
                    {"name": "termNo", "length": 9},
                    {"name": "DocName", "length": 30}
                ],
                "306": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "TreeTypNo", "length": 3},
                    {"name": "QS_Id", "length": 4},
                    {"name": "SortNo", "length": 3}
                ],
                "307": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "TreeTypNo", "length": 3},
                    {"name": "QS_Id", "length": 4},
                    {"name": "Node_ID", "length": 7},
                    {"name": "SortNo", "length": 3}
                ],
                "320": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "GenArtNo", "length": 5},
                    {"name": "NormTermNo", "length": 5},
                    {"name": "AssGrpNo", "length": 4},
                    {"name": "UsageNo", "length": 4},
                    {"name": "TermNo", "length": 9},
                    {"name": "OK_PC", "length": 1},
                    {"name": "OK_CV", "length": 1},
                    {"name": "OK_Eng", "length": 1},
                    {"name": "OK_Universal", "length": 1},
                    {"name": "OK_Ind", "length": 1},
                    {"name": "D_lete", "length": 1},
                    {"name": "OK_Axle", "length": 1}
                ],
                "323": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "NormTermNo", "length": 5},
                    {"name": "TermNo", "length": 9}
                ],
                "324": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "AssGrpNo", "length": 4},
                    {"name": "TermNo", "length": 9}
                ],
                "325": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "UsageNo", "length": 4},
                    {"name": "TermNo", "length": 9}
                ],
                "327": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "GenArtNo", "length": 5},
                    {"name": "SeqNo", "length": 3},
                    {"name": "LangNo", "length": 3},
                    {"name": "Term", "length": 60}
                ],
                "328": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "GenArtNo", "length": 5},
                    {"name": "SeqNo", "length": 3},
                    {"name": "CountryCode", "length": 3},
                    {"name": "CritNo", "length": 4},
                    {"name": "OnlyCrit", "length": 1},
                    {"name": "OnlyLnk", "length": 1},
                    {"name": "Exclude", "length": 1}
                ],
                "329": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "GenArtNo", "length": 5},
                    {"name": "SeqNo", "length": 3},
                    {"name": "CountryCode", "length": 3},
                    {"name": "CritNo", "length": 4},
                    {"name": "Art", "length": 1},
                    {"name": "Lnk", "length": 1},
                    {"name": "Exclude", "length": 1}
                ],
                "330": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "GenArtNo", "length": 5},
                    {"name": "SeqNo", "length": 3},
                    {"name": "SortNo", "length": 3},
                    {"name": "CritVal", "length": 3}
                ],
                "400": [
                    {"name": "ArtNo", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "GenArtNo", "length": 5},
                    {"name": "LnkTargetType", "length": 3},
                    {"name": "LnkTargetNo", "length": 9},
                    {"name": "SeqNo", "length": 9},
                    {"name": "D_leteFlag", "length": 1}
                ],
                "401": [
                    {"name": "ArtNo", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "GenArtNo", "length": 5},
                    {"name": "LnkTargetType", "length": 3},
                    {"name": "LnktargetNo", "length": 9},
                    {"name": "SeqNo", "length": 9},
                    {"name": "SortNo", "length": 2},
                    {"name": "CountryCode", "length": 3},
                    {"name": "InfType", "length": 3},
                    {"name": "FirstPage", "length": 1},
                    {"name": "TxtModNo", "length": 6},
                    {"name": "Exclude", "length": 1},
                    {"name": "D_leteFlag", "length": 1}
                ],
                "403": [
                    {"name": "ArtNo", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "GenArtNo", "length": 5},
                    {"name": "LnkTargetType", "length": 3},
                    {"name": "LnkTargetNo", "length": 9},
                    {"name": "SeqNo", "length": 9},
                    {"name": "CountryCode", "length": 3},
                    {"name": "Exclude", "length": 1},
                    {"name": "D_leteFlag", "length": 1}
                ],
                "404": [
                    {"name": "ArtNo", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "GenArtNo", "length": 5},
                    {"name": "LnkTargetType", "length": 3},
                    {"name": "LnkTargetNo", "length": 9},
                    {"name": "SortNo", "length": 9},
                    {"name": "D_leteFlag", "length": 1}
                ],
                "410": [
                    {"name": "ArtNo", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "GenArtNo", "length": 5},
                    {"name": "LnkTargetType", "length": 3},
                    {"name": "LnkTargetNo", "length": 9},
                    {"name": "SeqNo", "length": 9},
                    {"name": "SortNo", "length": 3},
                    {"name": "CritNo", "length": 4},
                    {"name": "CritVal", "length": 20},
                    {"name": "FirstPage", "length": 1},
                    {"name": "CountryCode", "length": 3},
                    {"name": "Exclude", "length": 1},
                    {"name": "D_leteFlag", "length": 1}
                ],
                "432": [
                    {"name": "ArtNo", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "GenArtNo", "length": 5},
                    {"name": "LnkTargetType", "length": 3},
                    {"name": "LnkTargetNo", "length": 9},
                    {"name": "SeqNo", "length": 9},
                    {"name": "CountryCode", "length": 3},
                    {"name": "SortNo", "length": 2},
                    {"name": "DocNo", "length": 9},
                    {"name": "DocType", "length": 2},
                    {"name": "Exclude", "length": 1},
                    {"name": "D_leteFlag", "length": 1}
                ],
                "532": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "NTypNo", "length": 9},
                    {"name": "KModNo", "length": 5},
                    {"name": "SortNo", "length": 4},
                    {"name": "CTermNo", "length": 9},
                    {"name": "ModYFrom", "length": 6},
                    {"name": "ModYTo", "length": 6},
                    {"name": "BodyType", "length": 3},
                    {"name": "EngType", "length": 3},
                    {"name": "KWFrom", "length": 4},
                    {"name": "KWTo", "length": 4},
                    {"name": "HPFrom", "length": 4},
                    {"name": "HPTo", "length": 4},
                    {"name": "CcmTech", "length": 5},
                    {"name": "Tonnage", "length": 5},
                    {"name": "AxleConfig", "length": 3},
                    {"name": "D_lete", "length": 1}
                ],
                "533": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "NTypNo", "length": 9},
                    {"name": "CountryCode", "length": 3},
                    {"name": "Exclude", "length": 1}
                ],
                "534": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "NTypNo", "length": 9},
                    {"name": "CountryCode", "length": 3},
                    {"name": "ModYFrom", "length": 6},
                    {"name": "ModYTo", "length": 6}
                ],
                "535": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "NTypNo", "length": 9},
                    {"name": "NTypSubNo", "length": 3},
                    {"name": "SortNo", "length": 3},
                    {"name": "Term", "length": 60},
                    {"name": "ModYFrom", "length": 6},
                    {"name": "ModYTo", "length": 6}
                ],
                "536": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "NTypNo", "length": 9},
                    {"name": "NTypSubNo", "length": 3},
                    {"name": "CountryCode", "length": 3},
                    {"name": "Exclude", "length": 1}
                ],
                "537": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "NTypNo", "length": 9},
                    {"name": "NTypSubNo", "length": 3},
                    {"name": "SeqNo", "length": 3},
                    {"name": "EngNo", "length": 5},
                    {"name": "ModYFrom", "length": 6},
                    {"name": "ModYTo", "length": 6},
                    {"name": "CountryCode", "length": 3},
                    {"name": "Exclude", "length": 1}
                ],
                "538": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "NTypNo", "length": 9},
                    {"name": "NTypSubNo", "length": 3},
                    {"name": "ManIDNo", "length": 5}
                ],
                "539": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "NTypNo", "length": 9},
                    {"name": "NTypSubNo", "length": 3},
                    {"name": "ManIDNo", "length": 5},
                    {"name": "CountryCode", "length": 3},
                    {"name": "Exclude", "length": 1}
                ],
                "540": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "NTypNo", "length": 9},
                    {"name": "NTypSubNo", "length": 3},
                    {"name": "SeqNo", "length": 2},
                    {"name": "Volt", "length": 2},
                    {"name": "CountryCode", "length": 3},
                    {"name": "Exclude", "length": 1}
                ],
                "541": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "DrivCabNo", "length": 5},
                    {"name": "ManNo", "length": 6},
                    {"name": "KModNo", "length": 5},
                    {"name": "CabDesign", "length": 30},
                    {"name": "CTermNo", "length": 9},
                    {"name": "Reserved", "length": 21},
                    {"name": "Size", "length": 3},
                    {"name": "ModYFrom", "length": 6},
                    {"name": "ModYTo", "length": 6},
                    {"name": "Length", "length": 7},
                    {"name": "Height", "length": 7},
                    {"name": "Width", "length": 7},
                    {"name": "D_lete", "length": 1}
                ],
                "542": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "DrivCabNo", "length": 5},
                    {"name": "CountryCode", "length": 3},
                    {"name": "Exclude", "length": 1}
                ],
                "543": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "NTypNo", "length": 9},
                    {"name": "NTypSubNo", "length": 3},
                    {"name": "SeqNo", "length": 2},
                    {"name": "DrivCabNo", "length": 5},
                    {"name": "ModYFrom", "length": 6},
                    {"name": "ModYTo", "length": 6},
                    {"name": "CountryCode", "length": 3},
                    {"name": "Exclude", "length": 1}
                ],
                "544": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "TransmNo", "length": 5},
                    {"name": "ManNo", "length": 6},
                    {"name": "Code", "length": 30},
                    {"name": "TransmType", "length": 3},
                    {"name": "ModYFrom", "length": 6},
                    {"name": "ModYTo", "length": 6},
                    {"name": "TrMin", "length": 5},
                    {"name": "TrMax", "length": 5},
                    {"name": "TrInv", "length": 5},
                    {"name": "TransmID", "length": 10},
                    {"name": "Speeds", "length": 2}
                ],
                "545": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "TransmNo", "length": 5},
                    {"name": "CountryCode", "length": 3},
                    {"name": "Exclude", "length": 1}
                ],
                "546": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "NTypNo", "length": 9},
                    {"name": "NTypSubNo", "length": 3},
                    {"name": "SeqNo", "length": 2},
                    {"name": "TransmNo", "length": 5},
                    {"name": "ModYFrom", "length": 6},
                    {"name": "ModYTo", "length": 6},
                    {"name": "CountryCode", "length": 3},
                    {"name": "Exclude", "length": 1}
                ],
                "550": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "NTypNo", "length": 9},
                    {"name": "NTypSubNo", "length": 3},
                    {"name": "SeqNo", "length": 2},
                    {"name": "WheelBase", "length": 6},
                    {"name": "AxlePos", "length": 3},
                    {"name": "CountryCode", "length": 3},
                    {"name": "Exclude", "length": 1}
                ],
                "551": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "NTypNo", "length": 9},
                    {"name": "NTypSubNo", "length": 3},
                    {"name": "SeqNo", "length": 2},
                    {"name": "SuspType", "length": 3},
                    {"name": "AxlePos", "length": 3},
                    {"name": "CountryCode", "length": 3},
                    {"name": "Exclude", "length": 1}
                ],
                "552": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "NTypNo", "length": 9},
                    {"name": "NTypSubNo", "length": 3},
                    {"name": "SeqNo", "length": 2},
                    {"name": "TyreType", "length": 3},
                    {"name": "AxlePos", "length": 3},
                    {"name": "CountryCode", "length": 3},
                    {"name": "Exclude", "length": 1}
                ],
                "553": [
                    {"name": "Reserved", "length": 22},
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "NTypNo", "length": 9},
                    {"name": "NTypSubNo", "length": 3},
                    {"name": "SeqNo", "length": 2},
                    {"name": "Chassis", "length": 10},
                    {"name": "CountryCode", "length": 3},
                    {"name": "Exclude", "length": 1}
                ],
                "554": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "ManIDNo", "length": 5},
                    {"name": "ManNo", "length": 6},
                    {"name": "ManID", "length": 20},
                    {"name": "D_lete", "length": 1}
                ],
                "555": [
                    {"name": "BrandNo", "length": 4},
                    {"name": "TableNo", "length": 3},
                    {"name": "ManIDNo", "length": 5},
                    {"name": "CountryCode", "length": 3},
                    {"name": "Exclude", "length": 1}
                ]
}
